pipeline:
  name: aiohttp_responses
  identifier: aiohttp_responses
  tags: {}
  template:
    templateRef: account.shared_library
    versionLabel: 1.1.0
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      stages:
        - stage:
            identifier: build_info
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  nodeSelector:
                    node_group: cpu
        - parallel:
            - stage:
                identifier: code_checks
                template:
                  templateInputs:
                    type: CI
                    variables:
                      - name: RUN_LINTER
                        type: String
                        value: "TRUE"
                      - name: isort
                        type: String
                        value: isort --check-only --profile black aiohttp_responses tests
                      - name: black
                        type: String
                        value: black --check aiohttp_responses tests
            - stage:
                identifier: build_containers
                type: CI
                variables:
                  - name: test_poetry_args
                    type: String
                    value: " "
                  - name: deploy_poetry_args
                    type: String
                    value: " "
                  - name: test_ram
                    type: String
                    value: 2G
                  - name: deploy_ram
                    type: String
                    value: 2G
        - parallel:
            - stage:
                identifier: unit_tests
                template:
                  templateInputs:
                    type: CI
                    variables:
                      - name: test_command
                        type: String
                        value: " "
                      - name: git_lfs
                        type: String
                        value: "FALSE"
                      - name: node_selector
                        type: String
                        value: cpu
                      - name: test_ram
                        type: String
                        value: 2G
                      - name: test_cpu
                        type: String
                        value: 1000m
            - stage:
                identifier: snyk_tests
                type: CI
                spec:
                  execution:
                    steps:
                      - parallel:
                          - step:
                              identifier: snyk_open_source
                              type: Snyk
                              spec:
                                advanced:
                                  fail_on_severity: critical
                      - step:
                          identifier: parse_code
                          type: Snyk
                          spec:
                            advanced:
                              fail_on_severity: critical
                variables:
                  - name: RUN_SNYK
                    type: String
                    value: <+input>.default(TRUE).allowedValues(TRUE,FALSE)
                  - name: container_ram
                    type: String
                    value: 2G
      variables:
        - name: repo
          type: String
          value: aiohttp_responses
        - name: service
          type: String
          value: aiohttp_responses
        - name: RUN_UNITTESTS
          type: String
          value: "FALSE"
  projectIdentifier: IPA_Release
  orgIdentifier: default
