repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/matthorgan/pre-commit-conventional-commits
    rev: 20fb9631be1385998138432592d0b6d4dfa38fc9
    hooks:
      - id: conventional-commit-check
        stages:
          - commit-msg
